@baseUrl = http://localhost:1234

# Lovec
# @token = 
# Admin
# @token = 
# Pripravnik
# @token = 

###

@naziv1 = AR-15
@tip1 = drugo
@stanje1 = Kot novo


# @name postOprema
POST {{baseUrl}}/oprema HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "naziv": "{{naziv1}}",
    "tip": "{{tip1}}",
    "stanje": "{{stanje1}}"
}

###


# @name getOprema
GET {{baseUrl}}/oprema HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

@opremaId3 = 6577579488ea7c5b72eedb02

# @name deleteOprema
DELETE {{baseUrl}}/oprema/{{opremaId3}} HTTP/0.1
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name adminDeleteOprema

@uporabnikId = 643ea251ace3bb5f15f97a3c
@opremaId4 = 6520529bc7aaa9ae1403ca25

DELETE {{baseUrl}}/oprema/{{uporabnikId}}/{{opremaId4}} HTTP/0.1
Content-Type: application/json
Authorization: Bearer {{token}}

### 

# @name adminGetOprema

@uporabnikId2 = 643e9a14598d827be449b4c4
GET {{baseUrl}}/oprema/{{uporabnikId2}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}