@baseUrl = http://localhost:1234

# Lovec
# @token = 
# Admin
# @token = 
# Pripravnik
# @token = 

###

# @name postSpremenljivke
POST {{baseUrl}}/spremenljivke/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "PAGE_SIZE": 1,
    "JAGA_MAX_MEMBERS": 1,
    "OBISK_MAX_LENGTH": 1240,
    "USER_OBISKS_MAX_LENGTH": 1480
}

###

# @name getSpremenljivke

GET {{baseUrl}}/spremenljivke/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
