@baseUrl = http://localhost:1234

###

@datum1 = 2019-01-02
@ure1 = 8
@opis1 = Hlev, listje, trava
@delo1 = Kidanje

# @name dnevnikVnesi
POST {{baseUrl}}/dnevniki/dodaj HTTP/1.1
Content-Type: application/json

{
    "datum": "{{datum1}}",
    "ure": "{{ure1}}",
    "opis": "{{opis1}}",
    "delo": "{{delo1}}"
}


###

@stran = 1

# @name dnevnikPripravnik

GET {{baseUrl}}/dnevniki/pripravnik/{{stran}} HTTP/1.1
Content-Type: application/json


###

@dnevnikId1 = 64b30ff767fcdab2277ce37d
@status1 = potrjen

# @name spremeniStatus

PATCH {{baseUrl}}/dnevniki/status HTTP/1.1
Content-Type: application/json

{
    "dnevnikId": "{{dnevnikId1}}",
    "status": "{{status1}}"
}


###

@datum2 = 2019-01-02

# @name dnevnik
GET {{baseUrl}}/dnevniki/mentor/{{datum2}} HTTP/1.1
Content-Type: application/json

{
    "datum": "{{datum2}}"
}