@baseUrl = http://localhost:1234

###

@naziv1 = AR-15
@tip1 = Avtomatska puška
@stanje1 = Kot novo


# @name postOprema
POST {{baseUrl}}/oprema/dodaj HTTP/1.1
Content-Type: application/json

{
    "naziv": "{{naziv1}}",
    "tip": "{{tip1}}",
    "stanje": "{{stanje1}}"
}

###


# @name getOprema
GET {{baseUrl}}/oprema/uporabnik HTTP/1.1
Content-Type: application/json

###

@opremaId3 = 64b4667e1360b2211d48a3a4

# @name deleteOprema
DELETE {{baseUrl}}/oprema/izbrisi HTTP/0.1
Content-Type: application/json

{
    "id": "{{opremaId3}}"
}