@baseUrl = http://localhost:1234

###

@email1 = kk@student.si
@geslo1 = 123

# @name postLogin
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "{{email1}}",
    "geslo": "{{geslo1}}"
}


###

@ime2 = Klemen
@priimek2 = Novak
@slika2 = omg.jpg
@rojstniDatum2 = 1999-01-01
@email2 = kn@student.si
@geslo2 = 123

# @name postRegister
POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
    "ime": "{{ime2}}",
    "priimek": "{{priimek2}}",
    "slika": "{{slika2}}",
    "rojstniDatum": "{{rojstniDatum2}}",
    "email": "{{email2}}",
    "geslo": "{{geslo2}}"
}

###
@id3 = 643e993545960e569b99ab64

# @name getUporabnik
GET {{baseUrl}}/uporabnik/{{id3}} HTTP/1.1
Content-Type: application/json