@baseUrl = http://localhost:1234

###

@zival1 = jejz
@teza1 = 12
@datum = 2023-07-15
@bolezni = [ "bolezen1", "bolezen2" ]

# @name postVplen
POST {{baseUrl}}/vpleni/dodaj HTTP/1.1
Content-Type: application/json

{
    "zival": "{{zival1}}",
    "teza": "{{teza1}}",
    "datum": "{{datum}}",
    "bolezni": {{bolezni}}
}

###

@stran2 = 1

# @name getVpleni
GET {{baseUrl}}/vpleni/moji/{{stran2}} HTTP/1.1
Content-Type: application/json

###

@datum3 = 2023-07-15

# @name getVplen

GET {{baseUrl}}/vpleni/{{datum3}} HTTP/1.1
Content-Type: application/json